#  Análisis Táctico, Perfilamiento SOM y Scouting (Moneyball)

## 1. Importación de la Base de Datos Clusterizada

En este script nos desvinculamos del entrenamiento geométrico de la red neuronal. Nuestro único objetivo es leer la base de datos resultante del **Script 5** y traducir las agrupaciones matemáticas (Arquetipos SOM) al idioma real del fútbol.

El código está diseñado para ser **dinámico**: detectará automáticamente cuántos clústeres se generaron en el paso anterior, permitiéndonos cambiar la configuración en el futuro sin tener que reescribir este cuaderno.

In [9]:
import pandas as pd
import numpy as np
from scipy.stats import norm

print("="*85)
print(" 🔄 INICIANDO SCRIPT 5: SCOUTING Y ANÁLISIS DE ARQUETIPOS")
print("="*85)

# 1. Cargar el Súper Dataset Definitivo (Ya trae crudos, precios, Z-Scores, PCA y Neuronas)
ruta_clusters = '/content/drive/MyDrive/dataset_final_clusters.csv'
df_clusters = pd.read_csv(ruta_clusters)

# 2. Calculamos dinámicamente el total de macro-clústeres para los reportes
total_clusters = df_clusters['Arquetipo_SOM'].nunique()

print(f"✅ ¡Base maestra cargada exitosamente!")
print(f"✅ Se detectaron automáticamente {total_clusters} Arquetipos Tácticos (Macro-Clústeres).")
print(f"✅ El dataset tiene {df_clusters.shape[1]} columnas (No se necesitan cruces adicionales).")
print("-" * 85)

# Vista previa para confirmar que tenemos todo en un solo lugar
display(df_clusters[['player', 'value_eur', 'xG P90', 'xG P90_z', 'PC1', 'ID_Neurona', 'Arquetipo_SOM']].head())

=====================================================================================
 🔄 INICIANDO SCRIPT 5: SCOUTING Y ANÁLISIS DE ARQUETIPOS
=====================================================================================
✅ ¡Base maestra cargada exitosamente!
✅ Se detectaron automáticamente 23 Arquetipos Tácticos (Macro-Clústeres).
✅ El dataset tiene 52 columnas (No se necesitan cruces adicionales).
-------------------------------------------------------------------------------------

,player,value_eur,xG P90,xG P90_z,PC1,ID_Neurona,Arquetipo_SOM
0,Aaron Cresswell,3000000.0,0.021197,-0.752355,1.226360,8-17,12
1,Aaron Lennon,625000.0,0.082510,0.452495,0.899998,5-7,17
2,Aaron Ramsey,26000000.0,0.234788,1.627059,5.103720,12-14,18
3,Abdelaziz Barrada,4300000.0,0.038600,-0.333183,-2.349870,0-5,11
4,Abdelaziz Barrada,4300000.0,0.133185,1.030335,2.253579,8-13,10

## 2. Radiografía de los Arquetipos (Z-Score y Percentiles)

Para entender qué rol táctico juega cada grupo en la cancha, agruparemos a los jugadores por su `Arquetipo_SOM` y calcularemos el promedio de sus métricas.

Dado que nuestros datos están estandarizados, utilizamos una doble lectura para máxima claridad:
1. **Z-Score (El Valor Crudo):** Indica a cuántas desviaciones estándar está el clúster respecto al jugador europeo promedio (0.00).
2. **Percentiles (La Traducción Visual):** Usando la Función de Distribución Acumulada Gaussiana (CDF), traducimos el Z-Score a un rango del 0 al 100. Un percentil 90 indica que ese grupo es superior al 90% de la liga en esa métrica.

Además, rankearemos los clústeres desde el que tiene mayor **Impacto Global** (los "todoterreno" o estrellas absolutas) hasta los de menor impacto (jugadores de rol muy específico o defensores rígidos).

---

### 🧠 El Éxito del Mapa Autoorganizado (SOM)

El mayor logro de esta red neuronal es que **destruyó las etiquetas tradicionales de posición**. En lugar de agrupar "delanteros con delanteros" o "defensas con defensas", el SOM entendió la complejidad del fútbol moderno: agrupó a los jugadores estrictamente por su **función táctica y comportamiento geométrico** en la cancha.

### 🌟 Radiografía de los Arquetipos de Élite

La diferenciación en el Top 4 demuestra cómo el algoritmo logró separar perfiles complejos con precisión quirúrgica:

* **Arquetipo 18 (Los Creadores Totales - #1):** Es la élite ofensiva absoluta. Agrupa a extremos y mediapuntas (Neymar, David Silva, Dybala) que dominan el último tercio. Tienen números de ataque, retención y creación estratosféricos (Percentil 90+ en asistencias, conducciones y faltas recibidas). Son el motor de peligro de sus equipos.
* **Arquetipo 3 (Los Metrónomos y Carrileros - #2):** Una genialidad matemática. El SOM agrupó a laterales ofensivos (Marcelo, Filipe Luís) con pivotes organizadores (Modrić, Fàbregas). Geométricamente, ambos roles hacen exactamente lo mismo: recuperar el balón, progresar líneas y mantener la estructura del equipo conectada (Percentil 90+ en centralidad, intercepciones y pases progresivos).
* **Arquetipo 10 (Los Atacantes Dinámicos - #3):** Perfiles como Antoine Griezmann o Lucas Moura. Son jugadores de alta movilidad que no solo definen, sino que conducen el balón largas distancias, rompen líneas y ayudan en la recuperación alta.
* **Arquetipo 14 (Los Depredadores de Área - #4):** Zlatan Ibrahimović, Romelu Lukaku. El algoritmo identificó a los finalizadores puros. Tienen un impacto brutal en la métrica de goles esperados (xG en Percentil 92), pero nula participación defensiva y baja creación. Viven de espaldas al arco y para definir.

### 🛡️ La Inteligencia de Aislación

La prueba definitiva de que el modelo funciona sin sesgos humanos está en el **Arquetipo 5 (#22)**. Sin que le entregáramos ninguna regla sobre posiciones nominales, el algoritmo agrupó a 103 porteros y los aisló en su propia neurona geométrica. Descubrió empíricamente la posición del arquero al detectar un patrón de ataque nulo, intercepciones nulas, pero un volumen atípico de pases largos progresivos.

In [10]:
import pandas as pd
import numpy as np
from scipy.stats import norm

# ==============================================================================
# 0. FUNCIÓN DE ARQUITECTURA DE POSICIONES (CORREGIDA)
# ==============================================================================
def clasificar_macro_posicion(posicion):
    pos = str(posicion).upper()

    # 1. MEDIOCAMPISTAS PRIMERO: Atrapa "Defensive Midfield", "Central Midfield", etc.
    # antes de que las palabras "Defensive" o "Central" los manden a otras líneas.
    if any(x in pos for x in ['MF', 'MID', 'MIDFIELDER', 'CM', 'AM', 'DM', 'RM', 'LM', 'VOLANTE', 'PIVOTE', 'MEDIO']):
        return '🧠 MEDIOCAMPISTAS'

    # 2. DELANTEROS
    elif any(x in pos for x in ['FW', 'DEL', 'ST', 'CF', 'LW', 'RW', 'EXTREMO', 'PUNTA', 'ATT', 'FORWARD']):
        return '🎯 DELANTEROS'

    # 3. DEFENSAS
    elif any(x in pos for x in ['DF', 'DEF', 'CB', 'LB', 'RB', 'WB', 'LATERAL', 'CENTRAL', 'BACK']):
        return '🛡️ DEFENSAS'

    # 4. Red de seguridad
    else:
        return '🧠 MEDIOCAMPISTAS'

# Aplicamos la función para crear la nueva columna.
df_clusters['Macro_Posicion'] = df_clusters['position_detail'].apply(clasificar_macro_posicion)


print("="*85)
print(f" 🏆 REPORTE DESCRIPTIVO: RADIOGRAFÍA DE LOS {total_clusters} ARQUETIPOS TÁCTICOS")
print("="*85)

# 1. DEFINICIÓN DE LAS DIMENSIONES TÁCTICAS (🚨 CORREGIDO CON SUFIJOS _z)
dimensiones_tacticas = {
    '⚽ ATAQUE / FINALIZACIÓN': ['xG P90_z', 'xG por Tiro_z'],
    '🧠 CREACIÓN / DISTRIBUCIÓN': ['Asistencias a Tiro P90_z', 'Pases Último Tercio P90_z', 'Pases Progresivos P90_z', '% Pases Seguridad_z', '% Centralidad Equipo_z'],
    '🛡️ DEFENSA / DESTRUCCIÓN': ['Tackles Ganados PAdj P90_z', 'Intercepciones PAdj P90_z', 'Recup. Último Tercio P90_z'],
    '🏃 MOVILIDAD / RETENCIÓN': ['Conducciones Progresivas P90_z', 'Pérdidas de Balón P90_z', '% Pases Bajo Presión_z', 'Faltas Recibidas P90_z']
}

columnas_metricas = [col for dims in dimensiones_tacticas.values() for col in dims]

# 2. CÁLCULO DE RENDIMIENTO E IMPACTO
# Score base de cada jugador (promedio de todas sus estadísticas ESTANDARIZADAS)
df_clusters['Score_Jugador'] = df_clusters[columnas_metricas].mean(axis=1)

# Agrupamos por clúster y promediamos sus variables _z
perfiles_descriptivos = df_clusters.groupby('Arquetipo_SOM')[columnas_metricas].mean()

# Calculamos el Impacto Global del clúster
perfiles_descriptivos['Impacto_Total_Cluster'] = perfiles_descriptivos.mean(axis=1)

# Calculamos el ranking de cada clúster para cada métrica individual
rankings_metricas = perfiles_descriptivos[columnas_metricas].rank(method='min', ascending=False)

# Ordenamos los clústeres del más influyente al menos influyente
clusters_ordenados = perfiles_descriptivos.sort_values(by='Impacto_Total_Cluster', ascending=False).index

# 3. BUCLE DINÁMICO DE IMPRESIÓN
for ranking_pos, cluster_id in enumerate(clusters_ordenados, start=1):

    # Extraemos información vital del clúster actual
    jugadores_del_grupo = df_clusters[df_clusters['Arquetipo_SOM'] == cluster_id]
    cantidad_jugadores = len(jugadores_del_grupo)

    medias_cluster = perfiles_descriptivos.loc[cluster_id]
    score_impacto_cluster = medias_cluster['Impacto_Total_Cluster']
    percentil_global = norm.cdf(score_impacto_cluster) * 100

    print(f"\n==================== #{ranking_pos} | ARQUETIPO TÁCTICO {cluster_id} ({cantidad_jugadores} jugadores) ====================")
    print(f"🌟 IMPACTO GLOBAL DEL GRUPO: {score_impacto_cluster:+.2f} Z-Score (Percentil Promedio: {percentil_global:.0f})")

    # --- CÁLCULO DE SCORES MACRO-DIMENSIONALES ---
    scores_dimensiones = {}
    for dim_nombre, vars_en_dim in dimensiones_tacticas.items():
        score_promedio = medias_cluster[vars_en_dim].mean()
        scores_dimensiones[dim_nombre] = score_promedio

    print("\n📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):")
    resumen_macro = " | ".join([f"{dim.split(' ')[1]} {norm.cdf(score)*100:.0f}%" for dim, score in scores_dimensiones.items()])
    print(f"   {resumen_macro}")

    # --- DESGLOSE DE VARIABLES CON RANKING TOP 3 ---
    print("\n   🔍 Desglose de Variables (Promedio del Grupo):")
    for dim_nombre, vars_en_dim in dimensiones_tacticas.items():
        print(f"      {dim_nombre}:")
        valores_dim = medias_cluster[vars_en_dim].sort_values(ascending=False)
        for var_name, valor_z in valores_dim.items():

            # Calculamos el percentil para determinar el color
            percentil = norm.cdf(valor_z) * 100

            # Escala de 5 colores según percentil
            if percentil < 20:
                indicador = "🔴" # Deficiente
            elif percentil < 40:
                indicador = "🟠" # Bajo la media
            elif percentil < 60:
                indicador = "🟡" # Promedio
            elif percentil < 80:
                indicador = "🟢" # Destacado
            else:
                indicador = "🔵" # Élite

            # Extraemos la posición en el ranking general para esta métrica
            posicion_ranking = rankings_metricas.loc[cluster_id, var_name]
            etiqueta_top = f"  [🏆 #{int(posicion_ranking)}]" if posicion_ranking <= 3 else ""

            # 🚨 NUEVO: Limpiamos el texto sacando el "_z" para la impresión en consola
            nombre_limpio = var_name.replace('_z', '')
            print(f"         {indicador} {nombre_limpio:<30} : {valor_z:+.2f} Z (Pc. {percentil:02.0f}){etiqueta_top}")

    # --- JUGADORES ÉLITE POR MACRO-POSICIÓN ---
    print("\n   ⭐ Jugadores Destacados por Línea de Juego:")

    orden_posiciones = ['🛡️ DEFENSAS', '🧠 MEDIOCAMPISTAS', '🎯 DELANTEROS']

    for macro_pos in orden_posiciones:
        # Filtramos los jugadores que pertenecen a esta macro-posición dentro del clúster
        jugadores_pos = jugadores_del_grupo[jugadores_del_grupo['Macro_Posicion'] == macro_pos]

        # Si hay jugadores de esta posición en este clúster
        if not jugadores_pos.empty:

            # Contamos cuántos hay de cada posición original exacta y lo unimos en un texto
            conteo_posiciones = jugadores_pos['position_detail'].value_counts()
            desglose_texto = " | ".join([f"{pos}: {count}" for pos, count in conteo_posiciones.items()])

            print(f"\n      {macro_pos} (Total: {len(jugadores_pos)}):")
            print(f"         📋 Desglose exacto: {desglose_texto}")

            # Extraemos e imprimimos el Top 5
            top_5_pos = jugadores_pos.sort_values(by='Score_Jugador', ascending=False).head(5)

            for index, row in top_5_pos.iterrows():
                nombre = row['player']
                equipo = row['team']
                pos_original = row['position_detail']
                score_individual = row['Score_Jugador']
                percentil_ind = norm.cdf(score_individual) * 100

                # Aplicamos la lógica visual a los jugadores
                if percentil_ind < 20:
                    ind_jugador = "🔴"
                elif percentil_ind < 40:
                    ind_jugador = "🟠"
                elif percentil_ind < 60:
                    ind_jugador = "🟡"
                elif percentil_ind < 80:
                    ind_jugador = "🟢"
                else:
                    ind_jugador = "🔵"

                print(f"         {ind_jugador} {nombre:<25} ({equipo:<12} | {pos_original:<6}) | Impacto Base: {score_individual:+.2f} Z (Pc. {percentil_ind:.0f})")
        else:
            # Insight táctico: El clúster no tiene jugadores de esta línea
            print(f"\n      {macro_pos}: [No hay jugadores de esta línea en este arquetipo]")

    print("-" * 85)

=====================================================================================
 🏆 REPORTE DESCRIPTIVO: RADIOGRAFÍA DE LOS 23 ARQUETIPOS TÁCTICOS
=====================================================================================

==================== #1 | ARQUETIPO TÁCTICO 18 (65 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.96 Z-Score (Percentil Promedio: 83)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 81% | CREACIÓN 86% | DEFENSA 74% | MOVILIDAD 86%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🔵 xG P90                         : +1.34 Z (Pc. 91)  [🏆 #3]
         🟢 xG por Tiro                    : +0.39 Z (Pc. 65)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🔵 Asistencias a Tiro P90         : +1.81 Z (Pc. 96)  [🏆 #1]
         🔵 Pases Último Tercio P90        : +1.76 Z (Pc. 96)  [🏆 #1]
         🔵 % Centralidad Equipo           : +0.95 Z (Pc. 83)  [🏆 #2]
         🟢 % Pases Seguridad              : +0.56 Z (Pc. 71)
         🟢 Pases Progresivos P90          : +0.27 Z (Pc. 61)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🔵 Recup. Último Tercio P90       : +1.72 Z (Pc. 96)  [🏆 #1]
         🟢 Tackles Ganados PAdj P90       : +0.26 Z (Pc. 60)
         🟡 Intercepciones PAdj P90        : -0.05 Z (Pc. 48)
      🏃 MOVILIDAD / RETENCIÓN:
         🔵 Conducciones Progresivas P90   : +1.59 Z (Pc. 94)  [🏆 #1]
         🔵 Pérdidas de Balón P90          : +1.40 Z (Pc. 92)  [🏆 #1]
         🔵 Faltas Recibidas P90           : +1.34 Z (Pc. 91)  [🏆 #1]
         🟡 % Pases Bajo Presión           : +0.08 Z (Pc. 53)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS: [No hay jugadores de esta línea en este arquetipo]

      🧠 MEDIOCAMPISTAS (Total: 64):
         📋 Desglose exacto: Right Wing: 17 | Left Wing: 16 | Center Attacking Midfield: 15 | Right Center Midfield: 4 | Left Defensive Midfield: 3 | Left Center Midfield: 3 | Right Defensive Midfield: 2 | Left Midfield: 2 | Right Midfield: 2
         🔵 Neymar da Silva Santos Junior (Barcelona    | Left Wing) | Impacto Base: +1.34 Z (Pc. 91)
         🔵 Franco Damián Vázquez     (Palermo      | Center Attacking Midfield) | Impacto Base: +1.31 Z (Pc. 91)
         🔵 Jonathan Viera Ramos      (Las Palmas   | Left Wing) | Impacto Base: +1.18 Z (Pc. 88)
         🔵 Fabián Ariel Orellana Valenzuela (Celta Vigo   | Right Wing) | Impacto Base: +1.16 Z (Pc. 88)
         🔵 David Josué Jiménez Silva (Manchester City | Center Attacking Midfield) | Impacto Base: +1.16 Z (Pc. 88)

      🎯 DELANTEROS (Total: 1):
         📋 Desglose exacto: Right Center Forward: 1
         🔵 Paulo Bruno Exequiel Dybala (Juventus     | Right Center Forward) | Impacto Base: +0.92 Z (Pc. 82)
-------------------------------------------------------------------------------------

==================== #2 | ARQUETIPO TÁCTICO 3 (97 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.67 Z-Score (Percentil Promedio: 75)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 44% | CREACIÓN 83% | DEFENSA 83% | MOVILIDAD 70%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🟡 xG P90                         : -0.03 Z (Pc. 49)
         🟠 xG por Tiro                    : -0.27 Z (Pc. 39)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🔵 % Centralidad Equipo           : +1.43 Z (Pc. 92)  [🏆 #1]
         🔵 Pases Último Tercio P90        : +1.35 Z (Pc. 91)  [🏆 #2]
         🔵 Asistencias a Tiro P90         : +1.03 Z (Pc. 85)  [🏆 #3]
         🔵 Pases Progresivos P90          : +0.98 Z (Pc. 84)  [🏆 #3]
         🟡 % Pases Seguridad              : -0.05 Z (Pc. 48)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🔵 Tackles Ganados PAdj P90       : +1.14 Z (Pc. 87)  [🏆 #2]
         🔵 Intercepciones PAdj P90        : +0.85 Z (Pc. 80)
         🔵 Recup. Último Tercio P90       : +0.84 Z (Pc. 80)
      🏃 MOVILIDAD / RETENCIÓN:
         🔵 Conducciones Progresivas P90   : +0.95 Z (Pc. 83)  [🏆 #3]
         🟢 Faltas Recibidas P90           : +0.74 Z (Pc. 77)
         🟢 Pérdidas de Balón P90          : +0.37 Z (Pc. 65)
         🟡 % Pases Bajo Presión           : +0.05 Z (Pc. 52)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS (Total: 39):
         📋 Desglose exacto: Left Back: 20 | Right Back: 16 | Left Wing Back: 2 | Right Wing Back: 1
         🔵 Senad Lulić               (Lazio        | Left Back) | Impacto Base: +0.95 Z (Pc. 83)
         🔵 Filipe Luís Kasmirski     (Atlético Madrid | Left Back) | Impacto Base: +0.91 Z (Pc. 82)
         🔵 Marcelo Vieira da Silva Júnior (Real Madrid  | Left Back) | Impacto Base: +0.87 Z (Pc. 81)
         🔵 Djibril Sidibé            (Lille        | Left Back) | Impacto Base: +0.85 Z (Pc. 80)
         🟢 Fábio Henrique Tavares    (AS Monaco    | Right Back) | Impacto Base: +0.79 Z (Pc. 79)

      🧠 MEDIOCAMPISTAS (Total: 58):
         📋 Desglose exacto: Right Center Midfield: 14 | Center Defensive Midfield: 11 | Left Center Midfield: 10 | Right Defensive Midfield: 10 | Left Defensive Midfield: 8 | Left Midfield: 3 | Center Attacking Midfield: 2
         🔵 Roberto Trashorras Gayoso (Rayo Vallecano | Right Defensive Midfield) | Impacto Base: +1.16 Z (Pc. 88)
         🔵 Francesc Fàbregas i Soler (Chelsea      | Right Defensive Midfield) | Impacto Base: +1.08 Z (Pc. 86)
         🔵 Lucas Rodrigo Biglia      (Lazio        | Center Defensive Midfield) | Impacto Base: +1.07 Z (Pc. 86)
         🔵 Jorge Resurrección Merodio (Atlético Madrid | Left Midfield) | Impacto Base: +1.02 Z (Pc. 85)
         🔵 Luka Modrić               (Real Madrid  | Right Center Midfield) | Impacto Base: +0.94 Z (Pc. 83)

      🎯 DELANTEROS: [No hay jugadores de esta línea en este arquetipo]
-------------------------------------------------------------------------------------

==================== #3 | ARQUETIPO TÁCTICO 10 (95 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.65 Z-Score (Percentil Promedio: 74)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 73% | CREACIÓN 73% | DEFENSA 71% | MOVILIDAD 79%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🔵 xG P90                         : +0.93 Z (Pc. 82)
         🟢 xG por Tiro                    : +0.27 Z (Pc. 61)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🔵 Asistencias a Tiro P90         : +1.26 Z (Pc. 90)  [🏆 #2]
         🔵 Pases Último Tercio P90        : +1.00 Z (Pc. 84)  [🏆 #3]
         🟢 % Pases Seguridad              : +0.62 Z (Pc. 73)
         🟢 % Centralidad Equipo           : +0.34 Z (Pc. 63)
         🟡 Pases Progresivos P90          : -0.19 Z (Pc. 42)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🔵 Recup. Último Tercio P90       : +1.16 Z (Pc. 88)  [🏆 #2]
         🟢 Tackles Ganados PAdj P90       : +0.35 Z (Pc. 64)
         🟡 Intercepciones PAdj P90        : +0.13 Z (Pc. 55)
      🏃 MOVILIDAD / RETENCIÓN:
         🔵 Pérdidas de Balón P90          : +1.14 Z (Pc. 87)
         🔵 Conducciones Progresivas P90   : +1.06 Z (Pc. 86)  [🏆 #2]
         🔵 Faltas Recibidas P90           : +0.87 Z (Pc. 81)  [🏆 #3]
         🟡 % Pases Bajo Presión           : +0.15 Z (Pc. 56)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS (Total: 2):
         📋 Desglose exacto: Right Wing Back: 1 | Left Wing Back: 1
         🟢 Marcos Alonso Mendoza     (Fiorentina   | Left Wing Back) | Impacto Base: +0.72 Z (Pc. 77)
         🟢 Juan Guillermo Cuadrado Bello (Juventus     | Right Wing Back) | Impacto Base: +0.72 Z (Pc. 76)

      🧠 MEDIOCAMPISTAS (Total: 90):
         📋 Desglose exacto: Right Wing: 26 | Center Attacking Midfield: 19 | Left Wing: 14 | Right Center Midfield: 11 | Left Center Midfield: 7 | Left Midfield: 7 | Right Midfield: 6
         🔵 Lucas Rodrigues Moura da Silva (Paris Saint-Germain | Right Wing) | Impacto Base: +1.06 Z (Pc. 85)
         🔵 Nabil Dirar               (AS Monaco    | Right Wing) | Impacto Base: +1.01 Z (Pc. 84)
         🔵 Nicolas Benezet           (Guingamp     | Left Midfield) | Impacto Base: +0.95 Z (Pc. 83)
         🔵 David Zurutuza Veillet    (Real Sociedad | Left Wing) | Impacto Base: +0.93 Z (Pc. 82)
         🔵 Sergio Gontán Gallardo    (Eibar        | Right Midfield) | Impacto Base: +0.91 Z (Pc. 82)

      🎯 DELANTEROS (Total: 3):
         📋 Desglose exacto: Center Forward: 2 | Left Center Forward: 1
         🔵 Antoine Griezmann         (Atlético Madrid | Left Center Forward) | Impacto Base: +0.90 Z (Pc. 82)
         🟢 Billy Ketkeophomphone     (Angers       | Center Forward) | Impacto Base: +0.66 Z (Pc. 74)
         🟢 Wayne Mark Rooney         (Manchester United | Center Forward) | Impacto Base: +0.64 Z (Pc. 74)
-------------------------------------------------------------------------------------

==================== #4 | ARQUETIPO TÁCTICO 14 (35 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.53 Z-Score (Percentil Promedio: 70)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 87% | CREACIÓN 64% | DEFENSA 50% | MOVILIDAD 80%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🔵 xG P90                         : +1.40 Z (Pc. 92)  [🏆 #2]
         🔵 xG por Tiro                    : +0.85 Z (Pc. 80)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🔵 Asistencias a Tiro P90         : +0.99 Z (Pc. 84)
         🟢 % Pases Seguridad              : +0.73 Z (Pc. 77)
         🟢 Pases Último Tercio P90        : +0.61 Z (Pc. 73)
         🟡 % Centralidad Equipo           : +0.06 Z (Pc. 52)
         🟠 Pases Progresivos P90          : -0.55 Z (Pc. 29)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🔵 Recup. Último Tercio P90       : +0.96 Z (Pc. 83)
         🟠 Tackles Ganados PAdj P90       : -0.35 Z (Pc. 36)
         🟠 Intercepciones PAdj P90        : -0.61 Z (Pc. 27)
      🏃 MOVILIDAD / RETENCIÓN:
         🔵 % Pases Bajo Presión           : +1.52 Z (Pc. 94)  [🏆 #2]
         🔵 Pérdidas de Balón P90          : +1.20 Z (Pc. 88)  [🏆 #3]
         🟢 Faltas Recibidas P90           : +0.63 Z (Pc. 74)
         🟡 Conducciones Progresivas P90   : -0.03 Z (Pc. 49)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS: [No hay jugadores de esta línea en este arquetipo]

      🧠 MEDIOCAMPISTAS (Total: 16):
         📋 Desglose exacto: Left Wing: 5 | Center Attacking Midfield: 4 | Right Wing: 3 | Right Center Midfield: 2 | Right Midfield: 1 | Left Defensive Midfield: 1
         🟢 Keisuke Honda             (AC Milan     | Right Midfield) | Impacto Base: +0.73 Z (Pc. 77)
         🟢 Cheikh N''Doye            (Angers       | Right Center Midfield) | Impacto Base: +0.69 Z (Pc. 76)
         🟢 Ivan Perišić              (Inter Milan  | Left Wing) | Impacto Base: +0.62 Z (Pc. 73)
         🟢 Wayne Routledge           (Swansea City | Left Wing) | Impacto Base: +0.61 Z (Pc. 73)
         🟢 Jean-Christophe Bahebeck  (Saint-Étienne | Left Wing) | Impacto Base: +0.48 Z (Pc. 68)

      🎯 DELANTEROS (Total: 19):
         📋 Desglose exacto: Center Forward: 10 | Left Center Forward: 6 | Right Center Forward: 3
         🔵 Zlatan Ibrahimović        (Paris Saint-Germain | Center Forward) | Impacto Base: +0.89 Z (Pc. 81)
         🔵 Stevan Jovetić            (Inter Milan  | Left Center Forward) | Impacto Base: +0.88 Z (Pc. 81)
         🟢 Cyril Théréau             (Udinese      | Left Center Forward) | Impacto Base: +0.82 Z (Pc. 79)
         🟢 Troy Deeney               (Watford      | Right Center Forward) | Impacto Base: +0.68 Z (Pc. 75)
         🟢 Romelu Lukaku Menama      (Everton      | Center Forward) | Impacto Base: +0.65 Z (Pc. 74)
-------------------------------------------------------------------------------------

==================== #5 | ARQUETIPO TÁCTICO 2 (94 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.46 Z-Score (Percentil Promedio: 68)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 84% | CREACIÓN 58% | DEFENSA 55% | MOVILIDAD 78%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🔵 xG P90                         : +1.29 Z (Pc. 90)
         🟢 xG por Tiro                    : +0.68 Z (Pc. 75)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🔵 % Pases Seguridad              : +1.02 Z (Pc. 85)  [🏆 #3]
         🟢 Asistencias a Tiro P90         : +0.81 Z (Pc. 79)
         🟢 Pases Último Tercio P90        : +0.42 Z (Pc. 66)
         🟠 % Centralidad Equipo           : -0.33 Z (Pc. 37)
         🔴 Pases Progresivos P90          : -0.87 Z (Pc. 19)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🔵 Recup. Último Tercio P90       : +1.12 Z (Pc. 87)  [🏆 #3]
         🟡 Tackles Ganados PAdj P90       : -0.24 Z (Pc. 41)
         🟠 Intercepciones PAdj P90        : -0.51 Z (Pc. 31)
      🏃 MOVILIDAD / RETENCIÓN:
         🔵 Pérdidas de Balón P90          : +1.37 Z (Pc. 91)  [🏆 #2]
         🔵 Faltas Recibidas P90           : +1.05 Z (Pc. 85)  [🏆 #2]
         🟢 Conducciones Progresivas P90   : +0.72 Z (Pc. 77)
         🟡 % Pases Bajo Presión           : -0.02 Z (Pc. 49)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS: [No hay jugadores de esta línea en este arquetipo]

      🧠 MEDIOCAMPISTAS (Total: 57):
         📋 Desglose exacto: Left Wing: 25 | Right Wing: 14 | Right Midfield: 7 | Center Attacking Midfield: 6 | Left Midfield: 3 | Right Center Midfield: 1 | Left Center Midfield: 1
         🟢 Paul-Georges Ntep de Madiba (Rennes       | Left Wing) | Impacto Base: +0.74 Z (Pc. 77)
         🟢 Max-Alain Gradel          (AFC Bournemouth | Left Midfield) | Impacto Base: +0.72 Z (Pc. 76)
         🟢 Jordan Ayew               (Aston Villa  | Left Wing) | Impacto Base: +0.66 Z (Pc. 75)
         🟢 Diego Alejandro Rolan Silva (Bordeaux     | Right Wing) | Impacto Base: +0.65 Z (Pc. 74)
         🟢 Yannis Salibur            (Guingamp     | Right Midfield) | Impacto Base: +0.65 Z (Pc. 74)

      🎯 DELANTEROS (Total: 37):
         📋 Desglose exacto: Center Forward: 23 | Right Center Forward: 8 | Left Center Forward: 6
         🟢 Alexandre Lacazette       (Lyon         | Center Forward) | Impacto Base: +0.83 Z (Pc. 80)
         🟢 Anthony Martial           (Manchester United | Center Forward) | Impacto Base: +0.82 Z (Pc. 79)
         🟢 Sergio Leonel Agüero del Castillo (Manchester City | Center Forward) | Impacto Base: +0.80 Z (Pc. 79)
         🟢 Diego da Silva Costa      (Chelsea      | Center Forward) | Impacto Base: +0.77 Z (Pc. 78)
         🟢 M''Baye Babacar Niang     (AC Milan     | Right Center Forward) | Impacto Base: +0.75 Z (Pc. 77)
-------------------------------------------------------------------------------------

==================== #6 | ARQUETIPO TÁCTICO 15 (96 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.37 Z-Score (Percentil Promedio: 64)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 40% | CREACIÓN 62% | DEFENSA 83% | MOVILIDAD 62%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🟡 xG por Tiro                    : -0.16 Z (Pc. 44)
         🟠 xG P90                         : -0.36 Z (Pc. 36)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🟢 % Centralidad Equipo           : +0.54 Z (Pc. 70)
         🟢 Pases Progresivos P90          : +0.51 Z (Pc. 70)
         🟢 Pases Último Tercio P90        : +0.49 Z (Pc. 69)
         🟡 Asistencias a Tiro P90         : +0.00 Z (Pc. 50)
         🟡 % Pases Seguridad              : -0.02 Z (Pc. 49)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🔵 Tackles Ganados PAdj P90       : +1.45 Z (Pc. 93)  [🏆 #1]
         🔵 Intercepciones PAdj P90        : +1.12 Z (Pc. 87)  [🏆 #1]
         🟢 Recup. Último Tercio P90       : +0.34 Z (Pc. 63)
      🏃 MOVILIDAD / RETENCIÓN:
         🟢 Faltas Recibidas P90           : +0.81 Z (Pc. 79)
         🟢 Conducciones Progresivas P90   : +0.38 Z (Pc. 65)
         🟡 Pérdidas de Balón P90          : +0.20 Z (Pc. 58)
         🟡 % Pases Bajo Presión           : -0.14 Z (Pc. 44)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS (Total: 41):
         📋 Desglose exacto: Right Back: 21 | Left Back: 18 | Right Center Back: 1 | Left Center Back: 1
         🟢 Serge Aurier              (Paris Saint-Germain | Right Back) | Impacto Base: +0.72 Z (Pc. 76)
         🟢 Rafael Pereira da Silva   (Lyon         | Right Back) | Impacto Base: +0.66 Z (Pc. 75)
         🟢 Ricardo Domingos Barbosa Pereira (OGC Nice     | Left Back) | Impacto Base: +0.65 Z (Pc. 74)
         🟢 Gregory van der Wiel      (Paris Saint-Germain | Right Back) | Impacto Base: +0.57 Z (Pc. 72)
         🟢 Luca Antonelli            (AC Milan     | Left Back) | Impacto Base: +0.54 Z (Pc. 71)

      🧠 MEDIOCAMPISTAS (Total: 55):
         📋 Desglose exacto: Left Defensive Midfield: 17 | Right Defensive Midfield: 17 | Center Defensive Midfield: 8 | Left Center Midfield: 5 | Right Center Midfield: 5 | Center Attacking Midfield: 2 | Right Midfield: 1
         🔵 Mousa Sidi Yaya Dembélé   (Tottenham Hotspur | Left Defensive Midfield) | Impacto Base: +0.88 Z (Pc. 81)
         🔵 Jan Kirchhoff             (Sunderland   | Center Defensive Midfield) | Impacto Base: +0.87 Z (Pc. 81)
         🟢 Pedro Pablo Hernández     (Celta Vigo   | Left Center Midfield) | Impacto Base: +0.78 Z (Pc. 78)
         🟢 Simone Missiroli          (Sassuolo     | Right Center Midfield) | Impacto Base: +0.72 Z (Pc. 76)
         🟢 Ignacio Camacho Barnola   (Málaga       | Right Defensive Midfield) | Impacto Base: +0.68 Z (Pc. 75)

      🎯 DELANTEROS: [No hay jugadores de esta línea en este arquetipo]
-------------------------------------------------------------------------------------

==================== #7 | ARQUETIPO TÁCTICO 22 (56 jugadores) ====================
🌟 IMPACTO GLOBAL DEL GRUPO: +0.32 Z-Score (Percentil Promedio: 62)

📊 PERFIL DEL CLÚSTER (Fuerzas Tácticas):
   ATAQUE 41% | CREACIÓN 62% | DEFENSA 66% | MOVILIDAD 70%

   🔍 Desglose de Variables (Promedio del Grupo):
      ⚽ ATAQUE / FINALIZACIÓN:
         🟡 xG P90                         : -0.06 Z (Pc. 48)
         🟠 xG por Tiro                    : -0.40 Z (Pc. 35)
      🧠 CREACIÓN / DISTRIBUCIÓN:
         🟢 Asistencias a Tiro P90         : +0.72 Z (Pc. 76)
         🟢 Pases Último Tercio P90        : +0.63 Z (Pc. 74)
         🟢 % Pases Seguridad              : +0.39 Z (Pc. 65)
         🟡 % Centralidad Equipo           : -0.09 Z (Pc. 46)
         🟡 Pases Progresivos P90          : -0.10 Z (Pc. 46)
      🛡️ DEFENSA / DESTRUCCIÓN:
         🟢 Recup. Último Tercio P90       : +0.71 Z (Pc. 76)
         🟢 Tackles Ganados PAdj P90       : +0.29 Z (Pc. 61)
         🟡 Intercepciones PAdj P90        : +0.23 Z (Pc. 59)
      🏃 MOVILIDAD / RETENCIÓN:
         🟢 Conducciones Progresivas P90   : +0.78 Z (Pc. 78)
         🟢 Faltas Recibidas P90           : +0.70 Z (Pc. 76)
         🟢 Pérdidas de Balón P90          : +0.64 Z (Pc. 74)
         🟡 % Pases Bajo Presión           : +0.02 Z (Pc. 51)

   ⭐ Jugadores Destacados por Línea de Juego:

      🛡️ DEFENSAS (Total: 13):
         📋 Desglose exacto: Right Back: 5 | Left Back: 4 | Left Wing Back: 3 | Right Wing Back: 1
         🟢 Alex Sandro Lobo Silva    (Juventus     | Left Wing Back) | Impacto Base: +0.78 Z (Pc. 78)
         🟢 Bruno da Silva Peres      (Torino       | Right Wing Back) | Impacto Base: +0.53 Z (Pc. 70)
         🟢 Sergio Escudero Palomo    (Sevilla      | Left Back) | Impacto Base: +0.49 Z (Pc. 69)
         🟢 Jorge Andújar Moreno      (Sevilla      | Right Back) | Impacto Base: +0.46 Z (Pc. 68)
         🟢 Fábio Alexandre da Silva Coentrão (AS Monaco    | Left Back) | Impacto Base: +0.42 Z (Pc. 66)

      🧠 MEDIOCAMPISTAS (Total: 43):
         📋 Desglose exacto: Left Midfield: 11 | Right Center Midfield: 6 | Right Wing: 5 | Left Center Midfield: 5 | Center Attacking Midfield: 4 | Left Defensive Midfield: 3 | Right Midfield: 3 | Left Wing: 3 | Center Defensive Midfield: 1 | Left Attacking Midfield: 1 | Right Defensive Midfield: 1
         🟢 Danilo Soddimo            (Frosinone    | Left Midfield) | Impacto Base: +0.65 Z (Pc. 74)
         🟢 Andrea Bertolacci         (AC Milan     | Left Defensive Midfield) | Impacto Base: +0.62 Z (Pc. 73)

## 3. Scouting de Élite: Buscando Gemelos Tácticos del "The Best" 15/16

En este bloque, ponemos a prueba el verdadero valor de nuestra arquitectura de datos aplicando un enfoque *Moneyball*. Tomaremos como referencia a los jugadores del XI Ideal de la FIFA de la temporada 2015/16 (incorporando a Gianluigi Buffon) para buscar a sus "clones" tácticos dentro del mercado.

**¿Cómo funciona este motor de búsqueda?**
Para asegurar que los jugadores recomendados no solo tengan estadísticas similares por casualidad, sino que compartan la misma esencia táctica, el algoritmo opera en tres fases:

1. **Aislamiento Topológico (Filtro SOM):** Primero, el modelo localiza la neurona exacta (Arquetipo SOM) habitada por la superestrella. La búsqueda de gemelos se restringe *exclusivamente* a los habitantes de ese mismo barrio geométrico.
2. **Similitud Geométrica (Distancia Euclidiana):** Dentro de esa neurona, el algoritmo calcula la distancia matemática exacta utilizando los 6 Componentes Principales (PCA) estandarizados, seleccionando a los 4 jugadores más cercanos en el hiperespacio.
3. **Contraste Financiero y Percentiles:** Finalmente, cruzamos las métricas brutas y calculamos el percentil de rendimiento global de cada jugador, emparejando esta información con sus valores de mercado y salarios.

**El objetivo final:** Demostrar que el modelo es capaz de detectar ineficiencias de mercado, encontrando jugadores de bajo perfil y bajo costo que logran un impacto táctico estadísticamente idéntico al de las superestrellas de clase mundial.

In [20]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist
from scipy.stats import percentileofscore
from IPython.display import display

print("="*85)
print(" 🏆 SCOUTING DE ÉLITE (VÍA SOM): BUSCANDO GEMELOS DEL 'THE BEST' 15/16")
print("="*85)

# 1. Definir el XI Ideal
xi_ideal = [
    'Gianluigi Buffon',
    'Daniel Alves', 'Gerard Piqué', 'Sergio Ramos', 'Marcelo Vieira',
    'Luka Modrić', 'Toni Kroos', 'Andrés Iniesta',
    'Lionel Andrés Messi', 'Luis Alberto Suárez', 'Cristiano Ronaldo'
]

# 2. Definir las columnas PCA y las Métricas Brutas a mostrar
columnas_pca = ['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6']

metricas_brutas = [
    'xG P90', 'xG por Tiro', 'Asistencias a Tiro P90', 'Pases Progresivos P90',
    'Pases Último Tercio P90', '% Pases Seguridad', '% Pases Bajo Presión',
    '% Centralidad Equipo', 'Conducciones Progresivas P90', 'Pérdidas de Balón P90',
    'Faltas Recibidas P90', 'Tackles Ganados PAdj P90', 'Intercepciones PAdj P90',
    'Recup. Último Tercio P90', 'Influencia Global P90'
]

df_busqueda = df_clusters.copy()

# 🚨 PARCHE PREVENTIVO: Asegurarnos de que las columnas PCA sean estrictamente números
for col in columnas_pca:
    df_busqueda[col] = pd.to_numeric(df_busqueda[col], errors='coerce')

for estrella in xi_ideal:
    # Buscar a la estrella
    jugador_target = df_busqueda[df_busqueda['player'].str.contains(estrella, case=False, na=False)]

    if jugador_target.empty:
        print(f"⚠️ {estrella} no fue encontrado en la base de datos.")
        print("-" * 85)
        continue

    # Extraer datos de la estrella
    indice_estrella = jugador_target.index[0]
    nombre_real = df_busqueda.loc[indice_estrella, 'player']
    neurona_estrella = df_busqueda.loc[indice_estrella, 'Arquetipo_SOM']

    # EL FILTRO SOM: Aislamos SOLO a los jugadores de su misma neurona
    df_misma_neurona = df_busqueda[df_busqueda['Arquetipo_SOM'] == neurona_estrella].copy()

    # Verificar que haya más jugadores en esa neurona
    if len(df_misma_neurona) <= 1:
        print(f"⚠️ {nombre_real} está solo en la Neurona {neurona_estrella}. No hay gemelos posibles en este arquetipo.")
        print("-" * 85)
        continue

    # 🚨 FIX: Extraer coordenadas PCA y OBLIGAR a que sean formato float (números decimales)
    coordenadas_estrella = df_misma_neurona.loc[indice_estrella, columnas_pca].values.astype(float).reshape(1, -1)
    coordenadas_neurona = df_misma_neurona[columnas_pca].values.astype(float)

    # Calcular distancia euclidiana intra-neurona
    distancias = cdist(coordenadas_estrella, coordenadas_neurona, metric='euclidean')[0]
    df_misma_neurona['Dist_Euclidiana_Intra_Neurona'] = distancias

    # Seleccionar a los 2 más cercanos dentro de la neurona
    gemelos = df_misma_neurona[df_misma_neurona['player'] != nombre_real].sort_values(by='Dist_Euclidiana_Intra_Neurona').head(4)

    # Preparar tabla comparativa
    df_comparativa = pd.concat([df_misma_neurona.loc[[indice_estrella]], gemelos])

    tabla_final = pd.DataFrame()
    tabla_final['Jugador'] = df_comparativa['player']
    tabla_final['Equipo'] = df_comparativa['team']
    tabla_final['posicion'] = df_comparativa['position_detail']



    # Manejo seguro de la edad
    tabla_final['Edad'] = pd.to_numeric(df_comparativa['age'], errors='coerce').fillna(0).astype(int)
    tabla_final['Neurona SOM'] = df_comparativa['Arquetipo_SOM']

    # Precios y Salarios (con conversión a numérico por seguridad)
    tabla_final['Valor de Mercado'] = pd.to_numeric(df_comparativa['value_eur'], errors='coerce').apply(
        lambda x: f"€ {x:,.0f}" if pd.notnull(x) else "Desconocido"
    )
    tabla_final['Salario Semanal'] = pd.to_numeric(df_comparativa['wage_eur'], errors='coerce').apply(
        lambda x: f"€ {x:,.0f}" if pd.notnull(x) else "Desconocido"
    )

    # Calcular percentiles globales (usando la base completa, no solo la neurona)
    for metrica in metricas_brutas:
        if metrica in df_busqueda.columns:
            valores_formateados = []
            for idx in df_comparativa.index:
                # Nos aseguramos de que el valor bruto sea numérico
                valor_bruto = float(df_busqueda.loc[idx, metrica])
                serie_metrica = pd.to_numeric(df_busqueda[metrica], errors='coerce').dropna()
                percentil = percentileofscore(serie_metrica, valor_bruto)
                valores_formateados.append(f"{valor_bruto:.2f} (Pc. {percentil:02.0f})")

            tabla_final[metrica] = valores_formateados

    print(f"\n🌟 OBJETIVO: {nombre_real.upper()} (Neurona SOM: {neurona_estrella})")
    display(tabla_final.set_index('Jugador').T)
    print("-" * 85)

print("✅ Scouting intracelular completado.")

=====================================================================================
 🏆 SCOUTING DE ÉLITE (VÍA SOM): BUSCANDO GEMELOS DEL 'THE BEST' 15/16
=====================================================================================

🌟 OBJETIVO: GIANLUIGI BUFFON (Neurona SOM: 5)

Jugador,Gianluigi Buffon,Kevin Trapp,Claudio Andrés Bravo Muñoz,Eugenio Lamanna,Samir Handanovič
Equipo,Juventus,Paris Saint-Germain,Barcelona,Genoa,Inter Milan
posicion,Goalkeeper,Goalkeeper,Goalkeeper,Goalkeeper,Goalkeeper
Edad,37,24,32,25,30
Neurona SOM,5,5,5,5,5
Valor de Mercado,"€ 9,000,000","€ 21,500,000","€ 17,500,000","€ 1,800,000","€ 19,000,000"
Salario Semanal,"€ 130,000","€ 120,000","€ 130,000","€ 25,000","€ 120,000"
xG P90,0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04)
xG por Tiro,0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04)
Asistencias a Tiro P90,0.00 (Pc. 03),0.00 (Pc. 03),0.00 (Pc. 03),0.08 (Pc. 14),0.00 (Pc. 03)
Pases Progresivos P90,17.13 (Pc. 70),18.27 (Pc. 76),18.67 (Pc. 77),21.99 (Pc. 88),21.07 (Pc. 85)
Pases Último Tercio P90,1.00 (Pc. 02),0.33 (Pc. 01),1.19 (Pc. 03),1.21 (Pc. 03),0.85 (Pc. 02)
% Pases Seguridad,1.69 (Pc. 06),0.91 (Pc. 05),5.58 (Pc. 06),0.28 (Pc. 02),1.42 (Pc. 06)
% Pases Bajo Presión,2.98 (Pc. 11),2.75 (Pc. 07),3.49 (Pc. 20),2.67 (Pc. 07),2.95 (Pc. 10)
% Centralidad Equipo,4.19 (Pc. 47),3.20 (Pc. 34),4.18 (Pc. 47),2.04 (Pc. 18),4.79 (Pc. 54)
Conducciones Progresivas P90,0.51 (Pc. 04),0.30 (Pc. 02),0.59 (Pc. 06),0.68 (Pc. 08),0.85 (Pc. 11)
Pérdidas de Balón P90,0.00 (Pc. 03),0.03 (Pc. 06),0.03 (Pc. 06),0.00 (Pc. 03),0.03 (Pc. 06)
Faltas Recibidas P90,0.00 (Pc. 01),0.09 (Pc. 04),0.03 (Pc. 02),0.08 (Pc. 04),0.14 (Pc. 07)
Tackles Ganados PAdj P90,0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04)
Intercepciones PAdj P90,0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04)
Recup. Último Tercio P90,0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04),0.00 (Pc. 04)
Influencia Global P90,61.12 (Pc. 12),63.55 (Pc. 13),82.23 (Pc. 24),65.21 (Pc. 14),65.73 (Pc. 14)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: DANIEL ALVES DA SILVA (Neurona SOM: 3)

Jugador,Daniel Alves da Silva,Claudio Marchisio,Yuri Berchiche Izeta,Issiaga Sylla,Milan Badelj
Equipo,Barcelona,Juventus,Real Sociedad,Gazélec Ajaccio,Fiorentina
posicion,Right Back,Center Defensive Midfield,Left Back,Left Back,Right Defensive Midfield
Edad,32,29,25,21,26
Neurona SOM,3,3,3,3,3
Valor de Mercado,"€ 16,000,000","€ 26,500,000","€ 1,800,000","€ 1,100,000","€ 6,500,000"
Salario Semanal,"€ 170,000","€ 150,000","€ 20,000","€ 8,000","€ 80,000"
xG P90,0.02 (Pc. 32),0.03 (Pc. 39),0.02 (Pc. 26),0.02 (Pc. 32),0.04 (Pc. 43)
xG por Tiro,0.04 (Pc. 24),0.03 (Pc. 15),0.03 (Pc. 15),0.04 (Pc. 20),0.04 (Pc. 19)
Asistencias a Tiro P90,0.66 (Pc. 67),0.91 (Pc. 81),0.62 (Pc. 65),0.74 (Pc. 73),1.28 (Pc. 91)
Pases Progresivos P90,17.71 (Pc. 73),23.32 (Pc. 91),21.48 (Pc. 86),19.04 (Pc. 78),24.06 (Pc. 92)
Pases Último Tercio P90,26.22 (Pc. 98),18.80 (Pc. 88),24.31 (Pc. 96),17.84 (Pc. 84),19.33 (Pc. 89)
% Pases Seguridad,39.02 (Pc. 56),38.37 (Pc. 54),33.81 (Pc. 38),32.80 (Pc. 35),33.50 (Pc. 37)
% Pases Bajo Presión,4.43 (Pc. 54),4.89 (Pc. 71),4.57 (Pc. 59),3.98 (Pc. 36),5.03 (Pc. 76)
% Centralidad Equipo,8.20 (Pc. 86),7.12 (Pc. 77),6.52 (Pc. 72),9.83 (Pc. 94),7.70 (Pc. 83)
Conducciones Progresivas P90,4.97 (Pc. 86),2.92 (Pc. 56),5.81 (Pc. 93),6.12 (Pc. 94),3.21 (Pc. 63)
Pérdidas de Balón P90,1.80 (Pc. 55),1.51 (Pc. 48),2.35 (Pc. 66),3.30 (Pc. 81),1.44 (Pc. 46)
Faltas Recibidas P90,0.88 (Pc. 51),0.96 (Pc. 56),1.25 (Pc. 70),0.68 (Pc. 38),0.96 (Pc. 56)
Tackles Ganados PAdj P90,1.91 (Pc. 95),1.65 (Pc. 92),1.29 (Pc. 82),1.78 (Pc. 94),1.57 (Pc. 90)
Intercepciones PAdj P90,1.58 (Pc. 84),1.85 (Pc. 91),2.54 (Pc. 98),2.25 (Pc. 96),2.43 (Pc. 97)
Recup. Último Tercio P90,1.62 (Pc. 89),1.96 (Pc. 96),1.49 (Pc. 85),0.97 (Pc. 60),1.24 (Pc. 75)
Influencia Global P90,227.80 (Pc. 98),216.60 (Pc. 97),172.36 (Pc. 87),163.61 (Pc. 82),233.46 (Pc. 99)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: GERARD PIQUÉ BERNABÉU (Neurona SOM: 1)

Jugador,Gerard Piqué Bernabéu,Thiago Emiliano da Silva,Laurent Koscielny,Ashley Williams,Aymeric Laporte
Equipo,Barcelona,Paris Saint-Germain,Arsenal,Swansea City,Athletic Club
posicion,Right Center Back,Right Center Back,Left Center Back,Left Center Back,Left Center Back
Edad,28,30,29,30,21
Neurona SOM,1,1,1,1,1
Valor de Mercado,"€ 29,500,000","€ 38,000,000","€ 17,500,000","€ 12,000,000","€ 26,000,000"
Salario Semanal,"€ 190,000","€ 200,000","€ 130,000","€ 60,000","€ 100,000"
xG P90,0.08 (Pc. 67),0.07 (Pc. 63),0.10 (Pc. 73),0.06 (Pc. 55),0.12 (Pc. 77)
xG por Tiro,0.17 (Pc. 94),0.13 (Pc. 85),0.16 (Pc. 92),0.13 (Pc. 83),0.15 (Pc. 89)
Asistencias a Tiro P90,0.14 (Pc. 21),0.23 (Pc. 31),0.28 (Pc. 36),0.27 (Pc. 35),0.20 (Pc. 27)
Pases Progresivos P90,28.11 (Pc. 97),30.56 (Pc. 99),22.41 (Pc. 89),23.43 (Pc. 91),24.49 (Pc. 93)
Pases Último Tercio P90,8.24 (Pc. 42),5.91 (Pc. 28),6.61 (Pc. 32),6.54 (Pc. 32),8.10 (Pc. 41)
% Pases Seguridad,29.68 (Pc. 27),21.97 (Pc. 14),18.85 (Pc. 10),23.14 (Pc. 16),27.30 (Pc. 23)
% Pases Bajo Presión,2.81 (Pc. 09),2.76 (Pc. 08),3.73 (Pc. 27),3.51 (Pc. 21),3.77 (Pc. 29)
% Centralidad Equipo,8.45 (Pc. 88),9.00 (Pc. 91),7.55 (Pc. 81),9.70 (Pc. 94),7.44 (Pc. 80)
Conducciones Progresivas P90,8.38 (Pc. 99),3.96 (Pc. 77),6.08 (Pc. 94),4.33 (Pc. 81),5.05 (Pc. 87)
Pérdidas de Balón P90,0.66 (Pc. 26),0.26 (Pc. 12),0.56 (Pc. 23),0.27 (Pc. 12),0.59 (Pc. 24)
Faltas Recibidas P90,0.42 (Pc. 21),0.76 (Pc. 43),0.81 (Pc. 46),0.41 (Pc. 21),1.06 (Pc. 62)
Tackles Ganados PAdj P90,0.97 (Pc. 65),1.41 (Pc. 85),1.13 (Pc. 74),1.17 (Pc. 76),1.05 (Pc. 70)
Intercepciones PAdj P90,1.64 (Pc. 86),2.29 (Pc. 96),2.23 (Pc. 95),1.97 (Pc. 92),1.94 (Pc. 92)
Recup. Último Tercio P90,0.14 (Pc. 15),0.26 (Pc. 23),0.12 (Pc. 14),0.11 (Pc. 13),0.43 (Pc. 31)
Influencia Global P90,212.92 (Pc. 97),236.83 (Pc. 99),160.50 (Pc. 80),158.89 (Pc. 79),152.50 (Pc. 74)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: SERGIO RAMOS GARCÍA (Neurona SOM: 1)

Jugador,Sergio Ramos García,Nicolás Hernán Otamendi,David Luiz Moreira Marinho,Íñigo Martínez Berridi,Shkodran Mustafi
Equipo,Real Madrid,Manchester City,Paris Saint-Germain,Real Sociedad,Valencia
posicion,Left Center Back,Right Center Back,Left Center Back,Left Center Back,Right Center Back
Edad,29,27,28,24,23
Neurona SOM,1,1,1,1,1
Valor de Mercado,"€ 34,000,000","€ 24,000,000","€ 21,000,000","€ 16,000,000","€ 23,000,000"
Salario Semanal,"€ 190,000","€ 180,000","€ 160,000","€ 60,000","€ 130,000"
xG P90,0.05 (Pc. 54),0.05 (Pc. 48),0.05 (Pc. 48),0.04 (Pc. 41),0.07 (Pc. 60)
xG por Tiro,0.06 (Pc. 41),0.05 (Pc. 30),0.08 (Pc. 57),0.07 (Pc. 44),0.08 (Pc. 58)
Asistencias a Tiro P90,0.28 (Pc. 35),0.13 (Pc. 20),0.20 (Pc. 28),0.07 (Pc. 13),0.10 (Pc. 17)
Pases Progresivos P90,27.11 (Pc. 96),21.82 (Pc. 87),28.25 (Pc. 98),23.04 (Pc. 90),24.85 (Pc. 93)
Pases Último Tercio P90,8.22 (Pc. 42),6.87 (Pc. 35),7.48 (Pc. 39),10.03 (Pc. 52),6.21 (Pc. 30)
% Pases Seguridad,17.40 (Pc. 08),18.26 (Pc. 09),23.77 (Pc. 17),26.15 (Pc. 21),21.63 (Pc. 14)
% Pases Bajo Presión,2.92 (Pc. 10),3.38 (Pc. 17),2.63 (Pc. 06),4.44 (Pc. 54),3.46 (Pc. 20)
% Centralidad Equipo,5.67 (Pc. 64),7.05 (Pc. 77),6.88 (Pc. 75),7.96 (Pc. 85),8.81 (Pc. 90)
Conducciones Progresivas P90,3.77 (Pc. 74),4.62 (Pc. 84),6.32 (Pc. 95),6.70 (Pc. 96),3.57 (Pc. 70)
Pérdidas de Balón P90,0.41 (Pc. 18),0.96 (Pc. 33),0.76 (Pc. 28),0.63 (Pc. 25),0.46 (Pc. 20)
Faltas Recibidas P90,1.38 (Pc. 75),0.99 (Pc. 58),0.76 (Pc. 43),0.89 (Pc. 51),0.73 (Pc. 41)
Tackles Ganados PAdj P90,1.29 (Pc. 82),1.99 (Pc. 97),1.24 (Pc. 79),1.09 (Pc. 72),1.66 (Pc. 92)
Intercepciones PAdj P90,3.07 (Pc. 100),3.18 (Pc. 100),2.07 (Pc. 94),2.63 (Pc. 98),2.72 (Pc. 99)
Recup. Último Tercio P90,0.23 (Pc. 21),0.17 (Pc. 17),0.16 (Pc. 16),0.30 (Pc. 25),0.36 (Pc. 28)
Influencia Global P90,180.87 (Pc. 90),168.91 (Pc. 85),229.46 (Pc. 99),143.50 (Pc. 68),154.72 (Pc. 76)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: MARCELO VIEIRA DA SILVA JÚNIOR (Neurona SOM: 3)

Jugador,Marcelo Vieira da Silva Júnior,Jérémy Pied,Luka Modrić,Djibril Sidibé,Toni Kroos
Equipo,Real Madrid,OGC Nice,Real Madrid,Lille,Real Madrid
posicion,Left Back,Right Back,Right Center Midfield,Left Back,Center Defensive Midfield
Edad,27,26,29,22,25
Neurona SOM,3,3,3,3,3
Valor de Mercado,"€ 22,500,000","€ 2,500,000","€ 41,500,000","€ 4,600,000","€ 54,500,000"
Salario Semanal,"€ 150,000","€ 25,000","€ 190,000","€ 30,000","€ 200,000"
xG P90,0.04 (Pc. 47),0.02 (Pc. 31),0.06 (Pc. 57),0.08 (Pc. 65),0.03 (Pc. 35)
xG por Tiro,0.06 (Pc. 42),0.04 (Pc. 21),0.05 (Pc. 32),0.07 (Pc. 47),0.04 (Pc. 24)
Asistencias a Tiro P90,1.51 (Pc. 95),0.83 (Pc. 79),1.96 (Pc. 98),0.89 (Pc. 81),1.49 (Pc. 95)
Pases Progresivos P90,23.55 (Pc. 91),22.12 (Pc. 88),24.77 (Pc. 93),18.89 (Pc. 78),26.45 (Pc. 95)
Pases Último Tercio P90,26.37 (Pc. 98),22.09 (Pc. 95),25.24 (Pc. 97),18.79 (Pc. 87),21.75 (Pc. 94)
% Pases Seguridad,36.90 (Pc. 49),39.21 (Pc. 56),36.21 (Pc. 46),38.39 (Pc. 54),34.68 (Pc. 41)
% Pases Bajo Presión,2.71 (Pc. 07),3.76 (Pc. 28),3.61 (Pc. 23),3.76 (Pc. 28),3.59 (Pc. 23)
% Centralidad Equipo,9.11 (Pc. 92),9.63 (Pc. 94),9.91 (Pc. 95),11.74 (Pc. 98),11.15 (Pc. 97)
Conducciones Progresivas P90,6.28 (Pc. 95),7.94 (Pc. 99),5.69 (Pc. 92),5.71 (Pc. 92),3.34 (Pc. 65)
Pérdidas de Balón P90,2.08 (Pc. 61),2.23 (Pc. 64),2.00 (Pc. 59),3.55 (Pc. 83),0.97 (Pc. 33)
Faltas Recibidas P90,1.41 (Pc. 77),1.37 (Pc. 75),2.33 (Pc. 95),1.61 (Pc. 83),1.88 (Pc. 89)
Tackles Ganados PAdj P90,1.89 (Pc. 95),2.17 (Pc. 98),1.25 (Pc. 80),1.92 (Pc. 95),1.94 (Pc. 96)
Intercepciones PAdj P90,2.72 (Pc. 99),2.03 (Pc. 94),2.46 (Pc. 98),2.27 (Pc. 96),2.02 (Pc. 93)
Recup. Último Tercio P90,1.75 (Pc. 93),0.98 (Pc. 61),1.70 (Pc. 92),0.89 (Pc. 57),1.10 (Pc. 69)
Influencia Global P90,217.83 (Pc. 98),208.69 (Pc. 96),245.49 (Pc. 99),179.66 (Pc. 90),258.45 (Pc. 100)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: LUKA MODRIĆ (Neurona SOM: 3)

Jugador,Luka Modrić,Andrés Iniesta Luján,Youssouf Sabaly,Marcelo Vieira da Silva Júnior,Toni Kroos
Equipo,Real Madrid,Barcelona,Nantes,Real Madrid,Real Madrid
posicion,Right Center Midfield,Left Center Midfield,Right Back,Left Back,Center Defensive Midfield
Edad,29,31,22,27,25
Neurona SOM,3,3,3,3,3
Valor de Mercado,"€ 41,500,000","€ 43,000,000","€ 2,200,000","€ 22,500,000","€ 54,500,000"
Salario Semanal,"€ 190,000","€ 220,000","€ 20,000","€ 150,000","€ 200,000"
xG P90,0.06 (Pc. 57),0.07 (Pc. 62),0.02 (Pc. 24),0.04 (Pc. 47),0.03 (Pc. 35)
xG por Tiro,0.05 (Pc. 32),0.08 (Pc. 56),0.04 (Pc. 19),0.06 (Pc. 42),0.04 (Pc. 24)
Asistencias a Tiro P90,1.96 (Pc. 98),1.14 (Pc. 88),0.92 (Pc. 82),1.51 (Pc. 95),1.49 (Pc. 95)
Pases Progresivos P90,24.77 (Pc. 93),23.75 (Pc. 92),22.72 (Pc. 89),23.55 (Pc. 91),26.45 (Pc. 95)
Pases Último Tercio P90,25.24 (Pc. 97),30.10 (Pc. 99),24.73 (Pc. 97),26.37 (Pc. 98),21.75 (Pc. 94)
% Pases Seguridad,36.21 (Pc. 46),35.80 (Pc. 45),34.42 (Pc. 40),36.90 (Pc. 49),34.68 (Pc. 41)
% Pases Bajo Presión,3.61 (Pc. 23),4.06 (Pc. 39),4.42 (Pc. 54),2.71 (Pc. 07),3.59 (Pc. 23)
% Centralidad Equipo,9.91 (Pc. 95),7.81 (Pc. 84),10.12 (Pc. 95),9.11 (Pc. 92),11.15 (Pc. 97)
Conducciones Progresivas P90,5.69 (Pc. 92),6.50 (Pc. 96),8.15 (Pc. 99),6.28 (Pc. 95),3.34 (Pc. 65)
Pérdidas de Balón P90,2.00 (Pc. 59),1.70 (Pc. 53),2.93 (Pc. 76),2.08 (Pc. 61),0.97 (Pc. 33)
Faltas Recibidas P90,2.33 (Pc. 95),1.99 (Pc. 92),1.48 (Pc. 79),1.41 (Pc. 77),1.88 (Pc. 89)
Tackles Ganados PAdj P90,1.25 (Pc. 80),1.80 (Pc. 94),1.58 (Pc. 90),1.89 (Pc. 95),1.94 (Pc. 96)
Intercepciones PAdj P90,2.46 (Pc. 98),0.66 (Pc. 46),1.48 (Pc. 81),2.72 (Pc. 99),2.02 (Pc. 93)
Recup. Último Tercio P90,1.70 (Pc. 92),1.62 (Pc. 90),1.59 (Pc. 89),1.75 (Pc. 93),1.10 (Pc. 69)
Influencia Global P90,245.49 (Pc. 99),235.43 (Pc. 99),197.78 (Pc. 94),217.83 (Pc. 98),258.45 (Pc. 100)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: TONI KROOS (Neurona SOM: 3)

Jugador,Toni Kroos,Gabriel Fernández Arenas,Jérémy Pied,Filipe Luís Kasmirski,Youssouf Sabaly
Equipo,Real Madrid,Atlético Madrid,OGC Nice,Atlético Madrid,Nantes
posicion,Center Defensive Midfield,Right Defensive Midfield,Right Back,Left Back,Right Back
Edad,25,31,26,29,22
Neurona SOM,3,3,3,3,3
Valor de Mercado,"€ 54,500,000","€ 11,500,000","€ 2,500,000","€ 14,500,000","€ 2,200,000"
Salario Semanal,"€ 200,000","€ 100,000","€ 25,000","€ 120,000","€ 20,000"
xG P90,0.03 (Pc. 35),0.01 (Pc. 22),0.02 (Pc. 31),0.01 (Pc. 18),0.02 (Pc. 24)
xG por Tiro,0.04 (Pc. 24),0.03 (Pc. 15),0.04 (Pc. 21),0.04 (Pc. 25),0.04 (Pc. 19)
Asistencias a Tiro P90,1.49 (Pc. 95),0.63 (Pc. 65),0.83 (Pc. 79),0.78 (Pc. 75),0.92 (Pc. 82)
Pases Progresivos P90,26.45 (Pc. 95),26.36 (Pc. 95),22.12 (Pc. 88),23.13 (Pc. 90),22.72 (Pc. 89)
Pases Último Tercio P90,21.75 (Pc. 94),24.37 (Pc. 97),22.09 (Pc. 95),29.85 (Pc. 99),24.73 (Pc. 97)
% Pases Seguridad,34.68 (Pc. 41),29.45 (Pc. 27),39.21 (Pc. 56),33.65 (Pc. 38),34.42 (Pc. 40)
% Pases Bajo Presión,3.59 (Pc. 23),3.75 (Pc. 28),3.76 (Pc. 28),4.44 (Pc. 55),4.42 (Pc. 54)
% Centralidad Equipo,11.15 (Pc. 97),11.88 (Pc. 99),9.63 (Pc. 94),11.83 (Pc. 99),10.12 (Pc. 95)
Conducciones Progresivas P90,3.34 (Pc. 65),3.29 (Pc. 64),7.94 (Pc. 99),7.82 (Pc. 99),8.15 (Pc. 99)
Pérdidas de Balón P90,0.97 (Pc. 33),1.24 (Pc. 40),2.23 (Pc. 64),2.13 (Pc. 62),2.93 (Pc. 76)
Faltas Recibidas P90,1.88 (Pc. 89),1.45 (Pc. 78),1.37 (Pc. 75),1.44 (Pc. 78),1.48 (Pc. 79)
Tackles Ganados PAdj P90,1.94 (Pc. 96),1.90 (Pc. 95),2.17 (Pc. 98),2.40 (Pc. 99),1.58 (Pc. 90)
Intercepciones PAdj P90,2.02 (Pc. 93),1.70 (Pc. 87),2.03 (Pc. 94),2.67 (Pc. 99),1.48 (Pc. 81)
Recup. Último Tercio P90,1.10 (Pc. 69),1.51 (Pc. 86),0.98 (Pc. 61),1.47 (Pc. 85),1.59 (Pc. 89)
Influencia Global P90,258.45 (Pc. 100),219.69 (Pc. 98),208.69 (Pc. 96),212.80 (Pc. 97),197.78 (Pc. 94)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: ANDRÉS INIESTA LUJÁN (Neurona SOM: 3)

Jugador,Andrés Iniesta Luján,Luka Modrić,Jorge Resurrección Merodio,Tomás Eduardo Rincón Hernández,Jean Michaël Seri
Equipo,Barcelona,Real Madrid,Atlético Madrid,Genoa,OGC Nice
posicion,Left Center Midfield,Right Center Midfield,Left Midfield,Right Defensive Midfield,Left Center Midfield
Edad,31,29,23,27,23
Neurona SOM,3,3,3,3,3
Valor de Mercado,"€ 43,000,000","€ 41,500,000","€ 31,000,000","€ 3,900,000","€ 3,800,000"
Salario Semanal,"€ 220,000","€ 190,000","€ 140,000","€ 60,000","€ 35,000"
xG P90,0.07 (Pc. 62),0.06 (Pc. 57),0.10 (Pc. 73),0.04 (Pc. 45),0.10 (Pc. 74)
xG por Tiro,0.08 (Pc. 56),0.05 (Pc. 32),0.08 (Pc. 56),0.05 (Pc. 31),0.08 (Pc. 51)
Asistencias a Tiro P90,1.14 (Pc. 88),1.96 (Pc. 98),1.88 (Pc. 98),0.96 (Pc. 83),1.29 (Pc. 92)
Pases Progresivos P90,23.75 (Pc. 92),24.77 (Pc. 93),18.81 (Pc. 77),16.95 (Pc. 70),20.57 (Pc. 83)
Pases Último Tercio P90,30.10 (Pc. 99),25.24 (Pc. 97),32.17 (Pc. 99),18.21 (Pc. 86),18.56 (Pc. 87)
% Pases Seguridad,35.80 (Pc. 45),36.21 (Pc. 46),41.46 (Pc. 62),30.37 (Pc. 29),42.80 (Pc. 66)
% Pases Bajo Presión,4.06 (Pc. 39),3.61 (Pc. 23),4.35 (Pc. 50),4.72 (Pc. 65),5.17 (Pc. 80)
% Centralidad Equipo,7.81 (Pc. 84),9.91 (Pc. 95),12.14 (Pc. 99),9.85 (Pc. 94),12.35 (Pc. 99)
Conducciones Progresivas P90,6.50 (Pc. 96),5.69 (Pc. 92),3.14 (Pc. 62),5.63 (Pc. 91),3.99 (Pc. 77)
Pérdidas de Balón P90,1.70 (Pc. 53),2.00 (Pc. 59),2.73 (Pc. 73),2.46 (Pc. 69),3.38 (Pc. 81)
Faltas Recibidas P90,1.99 (Pc. 92),2.33 (Pc. 95),1.85 (Pc. 88),1.89 (Pc. 89),1.71 (Pc. 86)
Tackles Ganados PAdj P90,1.80 (Pc. 94),1.25 (Pc. 80),1.57 (Pc. 90),1.34 (Pc. 84),1.07 (Pc. 71)
Intercepciones PAdj P90,0.66 (Pc. 46),2.46 (Pc. 98),1.34 (Pc. 76),1.04 (Pc. 63),1.10 (Pc. 66)
Recup. Último Tercio P90,1.62 (Pc. 90),1.70 (Pc. 92),1.82 (Pc. 94),1.59 (Pc. 88),1.07 (Pc. 67)
Influencia Global P90,235.43 (Pc. 99),245.49 (Pc. 99),222.69 (Pc. 98),191.14 (Pc. 93),254.60 (Pc. 100)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: LIONEL ANDRÉS MESSI CUCCITTINI (Neurona SOM: 18)

Jugador,Lionel Andrés Messi Cuccittini,Ross Barkley,Antonio Candreva,Alexis Alejandro Sánchez Sánchez,Riyad Mahrez
Equipo,Barcelona,Everton,Lazio,Arsenal,Leicester City
posicion,Right Wing,Center Attacking Midfield,Right Wing,Left Wing,Right Midfield
Edad,28,21,28,26,24
Neurona SOM,18,18,18,18,18
Valor de Mercado,"€ 111,000,000","€ 15,500,000","€ 23,000,000","€ 47,000,000","€ 4,600,000"
Salario Semanal,"€ 550,000","€ 60,000","€ 130,000","€ 230,000","€ 35,000"
xG P90,0.67 (Pc. 100),0.21 (Pc. 90),0.43 (Pc. 98),0.39 (Pc. 97),0.35 (Pc. 97)
xG por Tiro,0.13 (Pc. 85),0.08 (Pc. 56),0.13 (Pc. 83),0.10 (Pc. 70),0.14 (Pc. 86)
Asistencias a Tiro P90,1.85 (Pc. 98),1.49 (Pc. 95),1.25 (Pc. 91),1.83 (Pc. 98),1.61 (Pc. 96)
Pases Progresivos P90,18.93 (Pc. 78),13.67 (Pc. 56),10.62 (Pc. 44),14.19 (Pc. 58),10.85 (Pc. 45)
Pases Último Tercio P90,36.19 (Pc. 100),22.20 (Pc. 95),27.32 (Pc. 99),29.74 (Pc. 99),18.82 (Pc. 88)
% Pases Seguridad,43.41 (Pc. 67),46.23 (Pc. 74),48.34 (Pc. 78),45.77 (Pc. 73),39.69 (Pc. 58)
% Pases Bajo Presión,4.09 (Pc. 40),4.39 (Pc. 53),3.30 (Pc. 16),3.44 (Pc. 19),3.88 (Pc. 33)
% Centralidad Equipo,8.01 (Pc. 85),10.32 (Pc. 96),6.62 (Pc. 73),6.72 (Pc. 74),7.97 (Pc. 85)
Conducciones Progresivas P90,7.14 (Pc. 97),6.77 (Pc. 96),7.51 (Pc. 98),5.94 (Pc. 93),6.93 (Pc. 97)
Pérdidas de Balón P90,3.79 (Pc. 86),4.73 (Pc. 94),4.17 (Pc. 90),6.53 (Pc. 99),5.78 (Pc. 98)
Faltas Recibidas P90,2.51 (Pc. 97),2.37 (Pc. 96),2.05 (Pc. 92),2.73 (Pc. 98),2.65 (Pc. 97)
Tackles Ganados PAdj P90,0.42 (Pc. 28),0.60 (Pc. 42),0.33 (Pc. 23),0.93 (Pc. 63),0.80 (Pc. 55)
Intercepciones PAdj P90,0.32 (Pc. 27),0.31 (Pc. 26),0.63 (Pc. 44),0.57 (Pc. 41),0.83 (Pc. 53)
Recup. Último Tercio P90,1.60 (Pc. 89),2.28 (Pc. 98),2.24 (Pc. 98),3.04 (Pc. 100),2.16 (Pc. 98)
Influencia Global P90,231.27 (Pc. 99),200.53 (Pc. 95),187.21 (Pc. 92),222.93 (Pc. 98),167.54 (Pc. 84)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: LUIS ALBERTO SUÁREZ DÍAZ (Neurona SOM: 2)

Jugador,Luis Alberto Suárez Díaz,Lucas Pérez Martínez,Cristiano Ronaldo dos Santos Aveiro,Odion Jude Ighalo,Bojan Krkíc Pérez
Equipo,Barcelona,RC Deportivo La Coruña,Real Madrid,Watford,Stoke City
posicion,Center Forward,Center Forward,Left Wing,Left Center Forward,Center Attacking Midfield
Edad,28,26,30,26,24
Neurona SOM,2,2,2,2,2
Valor de Mercado,"€ 69,000,000","€ 10,000,000","€ 85,500,000","€ 2,700,000","€ 21,500,000"
Salario Semanal,"€ 300,000","€ 60,000","€ 475,000","€ 25,000","€ 70,000"
xG P90,0.78 (Pc. 100),0.43 (Pc. 98),0.89 (Pc. 100),0.46 (Pc. 99),0.21 (Pc. 90)
xG por Tiro,0.20 (Pc. 98),0.16 (Pc. 92),0.14 (Pc. 87),0.15 (Pc. 90),0.13 (Pc. 84)
Asistencias a Tiro P90,1.28 (Pc. 91),1.66 (Pc. 97),0.95 (Pc. 83),0.84 (Pc. 79),1.15 (Pc. 89)
Pases Progresivos P90,5.08 (Pc. 25),4.60 (Pc. 23),4.28 (Pc. 21),2.15 (Pc. 08),7.85 (Pc. 35)
Pases Último Tercio P90,16.67 (Pc. 80),17.90 (Pc. 85),16.80 (Pc. 81),8.34 (Pc. 43),14.85 (Pc. 74)
% Pases Seguridad,52.93 (Pc. 89),56.99 (Pc. 94),57.77 (Pc. 95),61.67 (Pc. 98),51.19 (Pc. 85)
% Pases Bajo Presión,2.85 (Pc. 09),3.19 (Pc. 14),4.12 (Pc. 41),3.30 (Pc. 16),3.41 (Pc. 18)
% Centralidad Equipo,4.05 (Pc. 45),5.99 (Pc. 67),5.00 (Pc. 57),4.38 (Pc. 49),4.34 (Pc. 49)
Conducciones Progresivas P90,2.44 (Pc. 46),4.16 (Pc. 79),5.70 (Pc. 92),2.58 (Pc. 49),5.51 (Pc. 90)
Pérdidas de Balón P90,3.86 (Pc. 87),4.24 (Pc. 90),2.96 (Pc. 77),6.28 (Pc. 99),3.79 (Pc. 86)
Faltas Recibidas P90,2.19 (Pc. 94),1.69 (Pc. 85),1.34 (Pc. 74),1.63 (Pc. 84),1.54 (Pc. 81)
Tackles Ganados PAdj P90,0.63 (Pc. 44),0.21 (Pc. 16),0.26 (Pc. 19),0.45 (Pc. 30),0.22 (Pc. 17)
Intercepciones PAdj P90,0.38 (Pc. 31),0.34 (Pc. 28),0.26 (Pc. 23),0.45 (Pc. 34),0.52 (Pc. 38)
Recup. Último Tercio P90,1.96 (Pc. 96),1.83 (Pc. 94),1.17 (Pc. 73),1.55 (Pc. 87),1.54 (Pc. 87)
Influencia Global P90,141.53 (Pc. 66),145.28 (Pc. 69),141.88 (Pc. 66),134.23 (Pc. 60),147.34 (Pc. 70)

-------------------------------------------------------------------------------------

🌟 OBJETIVO: CRISTIANO RONALDO DOS SANTOS AVEIRO (Neurona SOM: 2)

Jugador,Cristiano Ronaldo dos Santos Aveiro,Karim Benzema,Gonzalo Gerardo Higuaín,Bojan Krkíc Pérez,Lucas Pérez Martínez
Equipo,Real Madrid,Real Madrid,Napoli,Stoke City,RC Deportivo La Coruña
posicion,Left Wing,Center Forward,Center Forward,Center Attacking Midfield,Center Forward
Edad,30,27,27,24,26
Neurona SOM,2,2,2,2,2
Valor de Mercado,"€ 85,500,000","€ 46,500,000","€ 34,500,000","€ 21,500,000","€ 10,000,000"
Salario Semanal,"€ 475,000","€ 230,000","€ 190,000","€ 70,000","€ 60,000"
xG P90,0.89 (Pc. 100),0.76 (Pc. 100),0.75 (Pc. 100),0.21 (Pc. 90),0.43 (Pc. 98)
xG por Tiro,0.14 (Pc. 87),0.18 (Pc. 95),0.14 (Pc. 86),0.13 (Pc. 84),0.16 (Pc. 92)
Asistencias a Tiro P90,0.95 (Pc. 83),1.39 (Pc. 94),1.40 (Pc. 94),1.15 (Pc. 89),1.66 (Pc. 97)
Pases Progresivos P90,4.28 (Pc. 21),5.57 (Pc. 27),5.05 (Pc. 25),7.85 (Pc. 35),4.60 (Pc. 23)
Pases Último Tercio P90,16.80 (Pc. 81),17.10 (Pc. 82),13.06 (Pc. 67),14.85 (Pc. 74),17.90 (Pc. 85)
% Pases Seguridad,57.77 (Pc. 95),49.93 (Pc. 82),56.31 (Pc. 94),51.19 (Pc. 85),56.99 (Pc. 94)
% Pases Bajo Presión,4.12 (Pc. 41),4.22 (Pc. 44),4.47 (Pc. 56),3.41 (Pc. 18),3.19 (Pc. 14)
% Centralidad Equipo,5.00 (Pc. 57),3.00 (Pc. 31),3.72 (Pc. 41),4.34 (Pc. 49),5.99 (Pc. 67)
Conducciones Progresivas P90,5.70 (Pc. 92),2.96 (Pc. 57),3.14 (Pc. 61),5.51 (Pc. 90),4.16 (Pc. 79)
Pérdidas de Balón P90,2.96 (Pc. 77),2.79 (Pc. 74),4.72 (Pc. 93),3.79 (Pc. 86),4.24 (Pc. 90)
Faltas Recibidas P90,1.34 (Pc. 74),1.18 (Pc. 67),1.14 (Pc. 65),1.54 (Pc. 81),1.69 (Pc. 85)
Tackles Ganados PAdj P90,0.26 (Pc. 19),0.36 (Pc. 25),0.36 (Pc. 25),0.22 (Pc. 17),0.21 (Pc. 16)
Intercepciones PAdj P90,0.26 (Pc. 23),0.31 (Pc. 26),0.32 (Pc. 27),0.52 (Pc. 38),0.34 (Pc. 28)
Recup. Último Tercio P90,1.17 (Pc. 73),1.96 (Pc. 96),1.58 (Pc. 88),1.54 (Pc. 87),1.83 (Pc. 94)
Influencia Global P90,141.88 (Pc. 66),134.17 (Pc. 60),153.08 (Pc. 75),147.34 (Pc. 70),145.28 (Pc. 69)

-------------------------------------------------------------------------------------
✅ Scouting intracelular completado.

# 🏁 Conclusión y Trabajo Futuro: De la Descripción a la Predicción

## 🏆 El Hito Actual: Scouting Cuantitativo y "Moneyball" Táctico
Con la ejecución de este motor de búsqueda, hemos culminado la etapa descriptiva y diagnóstica de nuestro pipeline analítico. Al utilizar el equipo **FIFA The Best de la temporada 2015/16** como referencia, demostramos que la arquitectura de **PCA + Mapas Autoorganizados (SOM)** es capaz de leer el fútbol más allá de las posiciones nominales.

El modelo logró agrupar a los jugadores en "Arquetipos Tácticos" puros, permitiéndonos identificar asimetrías de mercado fascinantes: gemelos estadísticos que operaban en los mismos percentiles de rendimiento que las superestrellas mundiales, pero a una fracción de su valor de mercado (ej. perfiles como Lucas Pérez o Riyad Mahrez operando topológicamente cerca de Cristiano Ronaldo y Lionel Messi).

---

## 🚀 Trabajo Futuro: Backtesting y Validación Temporal (2016 - 2017)

El ecosistema de datos actual nos indica **quiénes rindieron como estrellas en el pasado**, pero el verdadero Santo Grial de la analítica deportiva es evaluar la sostenibilidad de ese rendimiento. Para la próxima iteración de este proyecto, el objetivo será transicionar hacia la **Analítica Predictiva y Validación de Mercado**, bajo la siguiente hoja de ruta:

### 1. Validación de Fichajes (El Veredicto del Mercado)
Se extraerá una lista de "Gemas Ocultas" (jugadores subvalorados con alto impacto táctico intra-neurona) detectadas por nuestro SOM al cierre de la temporada 15/16. Esta lista se cruzará con la base de datos de transferencias del verano de 2016 para responder una pregunta clave: *¿Ficharon los clubes de élite a los jugadores que nuestro algoritmo recomendaba en silencio?*

### 2. Backtesting de Rendimiento (Temporada 16/17)
Se integrará el dataset de eventos de la temporada 2016/2017 para evaluar la progresión de los "gemelos tácticos" descubiertos. El objetivo será medir:
* **Estabilidad del Arquetipo:** ¿Mantuvo el jugador su posición topológica en el mapa tras un cambio de club o de sistema táctico?
* **Proyección de Métricas:** ¿Qué tan sostenible es un salto repentino al percentil 90+ en métricas de finalización o creación?

### 3. Refinamiento Estadístico (Z-Scores Contextuales)
Para corregir el sesgo inherente de comparar perfiles defensivos contra ofensivos a nivel global, los futuros *scores* de impacto se calcularán de manera aislada. Se estandarizarán las métricas (Z-Score) exclusivamente dentro de cada Macro-Posición o intra-Arquetipo, garantizando que cada jugador sea evaluado estrictamente en su propio oficio y contexto.

> *El modelo actual ha demostrado que puede entender y decodificar el talento táctico. El próximo paso será demostrar que también puede anticiparlo.*